### ISSUE TITLE
Workforce_Typo_Errors 

### ISSUE THREAD

**Issue by AtharvaCPatil** [shauryanathan/malhar-live#7]
### **Typo format**
**<section_name>
<line_no.>
<corrected_phrase>**
note : corrected part of phrase in all caps

**Comment by AtharvaCPatil** [comment]
Admin
last line
...in THE case of....

**Comment by AtharvaCPatil** [comment]
Management
first line
..GIVE the test...

**Comment by xxchanjotxx** [comment]
solved
