### ISSUE TITLE
Events_Errors

### ISSUE THREAD

**Issue by AtharvaCPatil** [shauryanathan/malhar-live#8]
I think I've organised this pretty well :)

**Comment by AtharvaCPatil** [comment]
**GENERAL PROBLEMS**   
1. In brochure - **PRNC**, everywhere on the website - **PNRC**

---
**SUGGESTIONS:**
1. "know more" section event summary + description dono daal do 
2. Change "**no. of participants**" to "**participation type**" [_confusing terminology_]

---
**SPECIFIC PROBLEMS**
**1. Esports**
issue - for all other events, "know more" section is taken from the text just after the event title, but for **Esports it is taken from the event description section**

**2.  Malhar ICON**
issue - grammatical error -->  "know more" section1st line & brochure- ....YOU'D be hailed...... 
correction  - ...YOU'LL be.... 

**3. Rendezvous**
issue - Timings - Finals --> in brochure states 2.5hrs, on website it is 130min

**4. Once upon online**
issue - event will be live, on website, its showing pre-submission

**5. Back to the fusion**
issue - new line after "Frank Zappa. "

**6. Taal is well**
issue - add "(+30 seconds for introduction" to "Time" section

**7. A Tale of Two Tales**
issue - cross check time with brochure [_huge error here_]

**Comment by xxchanjotxx** [comment]
PRNC, 1,2.3,4,6, 7 solved

**Comment by xxchanjotxx** [comment]
> I think I've organised this pretty well :)

I swear man gg

**Comment by shauryanathan** [comment]
good job @AtharvaCPatil
